### ISSUE TITLE
App crushed in 2 places

### ISSUE THREAD

**Issue by ShaniItzhakov** [Noisy-Final-Project/Noisy-app#8]
The app crushed in my phone (with expo):
1. I signed up with a new account, then i signed in and it crushed after i clicked the button sign in.
2. I clicked on the map view reviews and then went back into the page chooseBussiness and it crushed.

**Comment by dean985** [comment]
@ShaniItzhakov  
As for 1, for me it worked.
Same for 2.

**Comment by ShaniItzhakov** [comment]
1 works now, was a problem with server.
